# Cấu hình cho Triplet
# Khi train nên load từ đây không nên tạo bên ngoài, chỉnh sửa thông số hay size gì cũng nên vào đâyđây



model:
  name: tSSN        
  backbone: resnet34            # Dùng ResNet
  feature_dim: 512              # Số chiều của vector đặc trưng đầu ra từ ResNet, muốn nhanh hơn thì giảm xuống
  kaggle_handle: None

training:
  batch_size: 32               # Số lượng ảnh trong mỗi batch
  learning_rate: 0.001         # Learning rate của optimizer
  early_stop: 3
  optimizer: adam              # Optimizer sử dụng 
  num_epochs: 100               # Số epoch train
  margin: 0.5                  # Margin cho triplet loss (threshold)
  scheduler: cosine            # Thêm scheduler để giảm learning rate dần


dataset:
  train_data_path: ./data/triplet/train/ # Đổi ở đây để load dataset
  val_data_path: ./data/triplet/val/  # Đổi ở đây để load dataset
  input_size: (220,150)             # Kích thước ảnh đầu vào (resize), có lẽ dùng cv2, x= 220, y = 150

device: cuda                   # Sử dụng GPU (CUDA)

logging:
  log_dir: ./logs/              # Thêm thư mục lưu log
  checkpoint_dir: ./checkpoints/ # Thêm thư mục lưu model checkpoint
  save_freq: 5                  # Lưu checkpoint mỗi 5 epoch
